spring.application.name: cloud-api-demo

server.port: 7200

#日志
logging:
  level:
    root: info
    top.oyoung.cloudapidemo.service.remote.UserService: debug

#服务注册中心
eureka:
  client:
    service-url:
      defaultZone:
#          http://young:123456@local1:7001/eureka/,http://young:123456@local2:7002/eureka/
          http://young:123456@localhost:7000/eureka/


feign:
  #ribbon 配置
  client:
    config:
      cloud-service-demo:
        loggerLevel: full
#        errorDecoder: com.example.SimpleErrorDecoder
#        retryer: com.example.SimpleRetryer
#        requestInterceptors:
#          - com.example.FooRequestInterceptor
#          - com.example.BarRequestInterceptor
#        decode404: false

#ribbon
#全局配置
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 1500
#  ServerListRefreshInterval: 2000
#  listOfServers: www.microsoft.com:80,www.yahoo.com:80,www.google.com:80
#具体某个client的配置
cloud-service-demo:
  ribbon:
    OkToRetryOnAllOperations: true
    MaxAutoRetries: 2               # Max number of retries on the same server (excluding the first try)
    MaxAutoRetriesNextServer: 1     # Max number of next servers to retry (excluding the first server)

#hystrix配置
feign.hystrix.enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000





